# Generated by Django 2.2.17 on 2021-01-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210129_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(),
        ),
    ]
